### PR TITLE
tested, changed time to date to align with discord format

### PR DESCRIPTION
**Pull request by Sarahtonein**
@Balugrizzly , as mentioned I tested this out utilizing the #testing channel in discord and confirmed that creations, updates, and aggregate posts are being sent. Is there any further information that can be identified from the bot that is running in production? Or can the image it is running on be rebuilt if that is a potential problem?

I have made a small change anyway from TIME to DATE so that it aligns more closely with the discord formatting that has been implemented.

### CODE REVIEW

**Comment by Balugrizzly** [comment]
@Sarahtonein 
Further information such as? 
Debug information?
Logs?
Stdout output?

Image can be rebuilt but images are deterministic so rebuilding will have the same result if no changes where made

TBH i am unsure what you wish to do here

**Comment by Sarahtonein** [comment]
> @Sarahtonein Further information such as? Debug information? Logs? Stdout output?
> 
> Image can be rebuilt but images are deterministic so rebuilding will have the same result if no changes where made
> 
> TBH i am unsure what you wish to do here

I have added further debug information to try and identify the issue, I noticed that the debug log was getting spammed by the handle_creations function, so I modified this. I am not having problems on my end though it is hard to diagnose further.

**Comment by Balugrizzly** [comment]
Why do you want to merge those into here?
Do you intend to run this in production? And derive something from it? If so could you tell me what?

**Review by Balugrizzly — COMMENTED** [review]
Not sure what you are trying to achieve here tbh.
Please tell me

**Comment by Balugrizzly** [comment]
Why was this closed?
Why is the branch not deleted?

**Pull request closed without merging**
